services:
  - type: web
    name: asistentruck-botam
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: asistentruck_botam_spa_production_jwt_master_secret_key_2026
      - key: PORT
        value: 10000
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
